In [12]:
import numpy as np
import pandas as pd
df = pd.read_csv('PDC_LDFZ_20200720_1_217_(PTF1_20200715)-SMB_TGA_underO2.txt',delimiter = '\t',header = 48, names = ['Time','Temp','Weight','Heat Flow','Temp diff','Temp diff V','Purge flow'])
df

,Time,Temp,Weight,Heat Flow,Temp diff,Temp diff V,Purge flow
0,0.000778,265.2631,15.80019,77.81750,4.385644,38.623840,100.00270
1,0.020833,264.8940,15.79999,77.58438,4.374386,38.509450,99.98900
2,0.058333,264.3630,15.79994,77.38811,4.367508,38.439720,99.98336
3,0.091667,263.9226,15.79975,77.14809,4.356518,38.328900,100.00790
4,0.125000,263.5210,15.79925,76.88916,4.343637,38.200740,99.95488
...,...,...,...,...,...,...,...
18997,651.841800,1000.3710,15.83734,-14.16762,0.371170,4.564737,100.00130
18998,651.879100,1000.3700,15.83735,-14.16889,0.371097,4.563836,99.98349
18999,651.916800,1000.3690,15.83738,-14.16901,0.371089,4.563742,100.00900
19000,651.950000,1000.3700,15.83742,-14.16831,0.371129,4.564238,100.01860
19001,-1.000000,1000.3700,0.00000,0.00000,0.000000,0.000000,0.00000

In [31]:
%matplotlib
import matplotlib.pyplot as plt
fig, ax1 = plt.subplots()

color = 'tab:red'
ax1.set_xlabel('Time (min)')
ax1.set_ylabel('Weight (mg)', color=color)
ax1.plot(df['Time'][:-1], df['Weight'][:-1], color=color)
ax1.tick_params(axis='y', labelcolor=color)

ax2 = ax1.twinx()  # instantiate a second axes that shares the same x-axis

color = 'tab:blue'
ax2.set_ylabel('Temperature ($^{\circ}$C)', color=color)  # we already handled the x-label with ax1
ax2.plot(df['Time'][:-1], df['Temp'][:-1], color=color, linestyle = '--')
ax2.tick_params(axis='y', labelcolor=color)

fig.tight_layout()  # otherwise the right y-label is slightly clipped
plt.show()
plt.savefig('TGA-BWO.png',dpi=200)

Using matplotlib backend: MacOSX

In [29]:
pct = (min(df['Weight'][:-1]))/max(df['Weight'][:-1])
print(pct)

0.9919575869730335